#!/bin/bash
export HOME="/home/ec2-user"
cat << EOF >> /etc/ecs/ecs.config
ECS_LOGLEVEL=info
ECS_LOG_ROLLOVER_TYPE=size
EOF

cat << EOF > /home/ec2-user/runtests.sh
cd /home/ec2-user/go/src/github.com/aws/amazon-ecs-agent
sudo systemctl stop ecs
make release
EOF

cat << EOF > /home/ec2-user/.vimrc
set number mouse=a colorcolumn=80 smartindent tabstop=4 laststatus=2 nocompatible
hi Comment ctermfg=darkgray
" Remember location in file
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
" Disable autoindent with Ctrl-p for pasting (insert mode only)
set pastetoggle=<C-P>
syntax on
EOF

yum install -y wget vim git jq aws-cli zsh gcc rsync util-linux-user
sudo chsh -s $(which zsh) ec2-user
usermod --shell $(which zsh) ec2-user
cat << \EOF > /home/ec2-user/.zshrc
autoload -Uz compinit colors add-zsh-hook
compinit -u
colors
typeset -U PATH
export HISTFILE=~/.zsh_history
export HISTSIZE=7500
export SAVEHIST=30000
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_SAVE_NO_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
setopt INC_APPEND_HISTORY
zstyle ':completion:*' menu select
git config --global alias.co checkout
git config --global alias.br branch
git config --global alias.ci commit
git config --global alias.st status
EOF
wget -O "/tmp/tig.rpm" "http://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/t/tig-2.4.0-1.el7.x86_64.rpm"
yum install -y /tmp/tig.rpm

wget -O "/tmp/go.tar.gz" "https://dl.google.com/go/go1.14.3.linux-amd64.tar.gz"
tar -C /usr/local -xzf /tmp/go.tar.gz
echo export GOPATH="/home/ec2-user/go"  >> /home/ec2-user/.zshrc
echo export PATH=$PATH:/usr/local/go/bin >> /home/ec2-user/.zshrc

mkdir -p /home/ec2-user/go/src/github.com/aws
git config --global pull.rebase true
git config --global branch.autosetuprebase always
cd /home/ec2-user/go/src/github.com/aws
git clone https://github.com/angelcar/amazon-ecs-agent.git
cd amazon-ecs-agent
git config --global pull.rebase true
git config --global branch.autosetuprebase always
git remote add upstream https://github.com/aws/amazon-ecs-agent.git
git fetch --all

#Install Prezto
cd /home/ec2-user
git clone --recursive https://github.com/sorin-ionescu/prezto.git "/home/ec2-user/.zprezto"
echo source "/home/ec2-user/.zprezto/init.zsh" >> /home/ec2-user/.zshrc
chown -R ec2-user /home/ec2-user
chgrp -R ec2-user /home/ec2-user

ln -s /home/ec2-user/.zprezto/runcoms/zlogin /home/ec2-user/.zlogin
ln -s /home/ec2-user/.zprezto/runcoms/zlogout /home/ec2-user/.zlogout
ln -s /home/ec2-user/.zprezto/runcoms/zpreztorc /home/ec2-user/.zpreztorc
ln -s /home/ec2-user/.zprezto/runcoms/zprofile /home/ec2-user/.zprofile
ln -s /home/ec2-user/.zprezto/runcoms/zshenv /home/ec2-user/.zshenv

echo "zstyle ':prezto:load' pmodule 'environment' 'terminal' 'editor' 'history' 'directory' 'spectrum' 'utility' 'completion' 'syntax-highlighting' 'git' 'autosuggestions' 'command-not-found' 'history-substring-search' 'prompt'" >> /home/ec2-user/.zpreztorc
